name: Compilar Java Personalizado

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar y ejecutar archivo
      run: |
        find . -name "camilo-suarez0.java" -exec javac {} \;
        find . -name "camilo_suarez0.class" -execdir java camilo_suarez0 \;
